level_1 = [
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXP   XXXX       XXXXX X",
"XXX    XXXX  XX   XXXXX X",
"XXX   XXXXXXXXX   XXX   X",
"XXX                    XX",
"XXXXXXXXXX     XXXXX  CXX",
"XXXXXXXXX    XXXXXXX   XX",
"XXXXXXXXX   XX     X   XX",
"XX   XXXX   XX     X   XX",
"XX  XXXXX  XXX         XX",
"XX  XXXXX  XXXXXXXXXXXXXX",
"XX                 XXXXXX",
"XXXXXXXXXXXXXX         XX",
"XXX  XXXXXXXXX  X  XXX XX",
"XXX        XXX  X  XXX XX", 
"XXXXXX     XXX  X  XXX XX",
"XXXXXX             XXX XX",
"XXXXXXXXXXXX  XXXXXXXX XX",
"XXXXXX        XXXXXXXX XX",
"XX            XXXXXXXX XX",
"XX XXX        XXXXXXXX XX",
"XX XXX                 XX",
"XX XXXXXXX XXXXXXXXXXXXXX",
"XX         XXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
]


#test